10-footer-component-KhadijaHaji
ShayanMahnam/lentegeur-hospital-facility-board pull request #16
Opened 2023-06-19 18:00 UTC by KhadijaHaji

## Description

The Footer component has been amended to include the headings included in the wireframe and styled.

## Related to

issue #10 

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

2023-06-19 19:53 UTC, bazmurphy requested changes
Hi @KhadijaHaji 

First PR of the Project 🥳 

Here is my Review

These are my suggestions, and its a discussion, I am happy to communicate on these points and clarify anything, and please stand your ground if you are doing things for specific reasons, just try to explain it etc.

Please have a play with the suggestions and see how they change things.
And I recommend (whilst working) using this line temporarily, because it really helps you to see whats happening with all the box models and why.
```
* {
  border: 1px dotted black;
}
```

Please mention me like @bazmurphy when replying so I get notifications

Thanks!

2023-06-19 19:53 UTC, bazmurphy commented on client/src/components/Footer/Footer.css
> +}
```suggestion
footer {
    display: flex;
    flex-direction: column;
    gap: 10px; /* or whatever gap you want */
    padding: 20px 20px 40px 20px;
    background-color:#B3B3B3;
}
```
we have a footer and then a div inside of it which are fulfilling the same function and can be combined into one

but maybe there is another reason that im missing

there are some adjustments suggestions here that are relative to the comments below

2023-06-19 19:53 UTC, bazmurphy commented on client/src/components/Footer/Footer.css
> +}
is this to offset each item from one another in the mobile first column mode? 
in that case we can use gap (see above and below)

or is this to provide padding at the bottom of the entire footer container in desktop? 
in which case we can add that to the footer element (see above)

2023-06-19 19:53 UTC, bazmurphy commented on client/src/components/Footer/Footer.css
> +    margin: 0;
everything has padding: 0 and margin: 0 globally applied to it by the `RootLayout.css` which might eventually become a global css stylesheet

2023-06-19 19:53 UTC, bazmurphy commented on client/src/components/Footer/Footer.css
> +    }
```suggestion
    /* Desktop version */
    footer {
        flex-direction: row;
        justify-content: space-evenly;
        gap: 20px; /* or whatever gap you want */
    }
```
we can use this on the footer if we apply the above logic.
the gap will change according to mobile/desktop
the justify-content prevents the need for the flex-basis percentages

and about the wrap, is the logic when the screen gets too small for 4 columns and you want it to snap over underneath? this is a good thing for us to think about re: breakpoints.

just thoughts:
maybe grid would be better then eg.
1 col x 4 row in mobile
2 col x 2 row in tablet
4 col x 1 row in desktop

2023-06-19 19:53 UTC, bazmurphy commented on client/src/components/Footer/Footer.css
> +}
percentages get funky with gaps

because it's trying to fill 100% of the container and the gaps in between cause a problem with that which means you end up with overspill

see above (where i added justify-content: space-evenly on the desktop version) and you could maybe specify a justify-content on the mobile to be explicit.

2023-06-19 19:53 UTC, bazmurphy commented on client/src/components/Footer/Footer.jsx
> +import React from "react";
we don't need this import statement in modern versions of react anymore

2023-06-19 19:53 UTC, bazmurphy commented on client/src/components/Footer/Footer.jsx
> +          <p>Lorem Ipsum is simply dummy text of the printing</p>
There is a way to edit your VSCode settings so you can use "Emmet" in jsx files, so your intellisense will work with lorem10 and then you press enter and it gives you a 10 word sentence of lorem, this might be useful for you on this project

2023-06-19 19:53 UTC, bazmurphy commented on client/src/components/Footer/Footer.jsx
> +              <a href="#">Service 1</a>
Will these eventually link to something like:

/services#1 as in the id of the heading of each service from the Services Page?

maybe worth pre-populating them to avoid the a11y eslint accessibility error

I will look up how to achieve that with Link from React Router, it might be simple

2023-06-19 19:53 UTC, bazmurphy commented on client/src/components/Footer/Footer.jsx
> +              <NavLink to="/">Home</NavLink>
Just to explain the difference between Link and NavLink from React Router.
The NavLink ahs an "active" class applied to it when the route of the page matches it

If you would like that benefit we can keep these as NavLinks otherwise they can be Link

2023-06-20 17:10 UTC, KhadijaHaji commented on client/src/components/Footer/Footer.css
> +}
I understand what you mean, I'll commit your suggestion thanks! @bazmurphy

2023-06-20 17:17 UTC, KhadijaHaji commented on client/src/components/Footer/Footer.css
> +    margin: 0;
great, thanks, I've removed these now.

2023-06-20 17:21 UTC, KhadijaHaji commented on client/src/components/Footer/Footer.css
> +    }
I've committed the changes you've suggested.
The first point you made about flex-wrap is why I used it.

2023-06-20 17:34 UTC, KhadijaHaji commented on client/src/components/Footer/Footer.jsx
> +          <p>Lorem Ipsum is simply dummy text of the printing</p>
IT WORKS🤣

2023-06-20 17:54 UTC, KhadijaHaji commented on client/src/components/Footer/Footer.jsx
> +              <a href="#">Service 1</a>
I've linked them to the ServicesPage for now then I will populate it with the id of each heading of the ServicePage.

2023-06-20 17:55 UTC, KhadijaHaji commented on client/src/components/Footer/Footer.jsx
> +              <NavLink to="/">Home</NavLink>
I've changed the NavLink to Link.

2023-06-20 21:56 UTC, ShayanMahnam commented on client/src/components/Footer/Footer.jsx
> +      <div className="footer-container">
if you delete this div (footer-container) everything will work perfectly

2023-06-22 10:11 UTC, KhadijaHaji commented on client/src/components/Footer/Footer.jsx
> +      <div className="footer-container">
Thanks @ShayanMahnam , I've removed it.

2023-06-24 07:34 UTC, bazmurphy approved these changes
Good job 😎 It has improved nicely 😄
(Just a few minor comments to address)


Before you merge: 

1. Please make sure you enable that prettier setting to format your code

2. Please make sure you update this branch with the latest `development` branch before you merge the PR

1. switch to the development branch
`git switch development`
get the latest version of development
`git fetch origin`
`git pull origin development`

2. then switch back to your branch
`git switch 10-footer-component`
and merge the latest version of development into your branch
`git merge development`
and it will add that as a (merge) commit to your branch

you can then merge this PR 👍

2023-06-24 07:34 UTC, bazmurphy commented on client/src/components/Footer/Footer.css
> +    font-size: 12px;
it might be better to leave this font sizing to the global style sheet where in mobile it will be 14px and desktop 16px and so will be consistent with the rest of the text

(unless you specifically want it smaller on the footer)

2023-06-24 07:34 UTC, bazmurphy commented on client/src/components/Footer/Footer.css
> +    font-size: 15px;
same as above re: font sizes

2023-06-24 07:34 UTC, bazmurphy commented on client/src/components/Footer/Footer.css
> +        gap: 10px;
this is the gap between the heading and the list in Desktop 
but it's smaller than the one for Mobile (currently 15px)

so either we can make it the same 

or have the mobile less and the desktop more... up to you

2023-06-24 07:34 UTC, bazmurphy commented on client/src/components/Footer/Footer.css
> +    gap: 15px;
see comment below re: gap in the media query

2023-06-24 07:34 UTC, bazmurphy commented on client/src/components/Footer/Footer.css
> +    background-color: hsl(0, 0%, 70%);
we can use the global variables now
```suggestion
    background-color: var(--gray70);
```

2023-06-24 07:34 UTC, bazmurphy commented on client/src/components/Footer/Footer.css
> +    background-color: hsl(0, 0%, 70%);
(don't commit this suggestion using the button above, just change it in your own code)

2023-06-25 12:58 UTC, KhadijaHaji commented on client/src/components/Footer/Footer.css
> +    background-color: hsl(0, 0%, 70%);
Great, all done.

2023-06-28 20:26 UTC, merged