11 - Get Involved Page - bazmurphy
ShayanMahnam/lentegeur-hospital-facility-board pull request #20
Opened 2023-06-20 16:56 UTC by bazmurphy

## Description

This PR creates version 1.0 of the **Getting Involved Page** using the version 1.0 Wireframes.
I have tried to emulate the Wireframes as closely as possible considering they are not 100% accurate.

I have tried to create it with React componentisation philosophy in mind.
The Styling is difficult because there is no generally agreed CSS philosophy we are undertaking, this means I have used classNames excessively to guarantee no conflicts.

This PR includes:
- adding the `GetInvolvedPage`
- adding the component `Donate`
- adding the component `Volunteer`
  - adding the subcomponent `VolunteerForm`
  - uncontrolled Form by design
  - mock submission handling for testing
- CSS Styling for Mobile First and Desktop (but **we haven't agreed on a breakpoint**)  

**I am looking for feedback on this Pull Request.**

## Related to

Issue #18

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have carefully reviewed my own code
- [x] I have commented my code
- [x] ~I have updated any documentation~ Not neccessary

2023-06-20 21:39 UTC, VitalinaKuzmenko approved these changes
Baz, well done! 
I don't see here any topic which I wanted to discuss in details:D Everything looks great for me!

2023-06-20 22:00 UTC, ShayanMahnam commented on client/src/pages/GetInvolvedPage/GetInvolvedPage.css
> +.get-involved-section > h1 {
the head title can be in global css because we have it on all of our pages

2023-06-20 22:03 UTC, ShayanMahnam commented on client/src/pages/GetInvolvedPage/GetInvolvedPage.css
> +	text-align: center; /* do we want this centered or is justify better? */
depends on the context length she will provide, for now, the center is ok

2023-06-21 05:37 UTC, bazmurphy commented on client/src/pages/GetInvolvedPage/GetInvolvedPage.css
> +		padding: 20px 40px;
i put this here temporarily
actually there exists a `main` element in `RootLayout.jsx`
and these sorts of rules should be applied there
to either `main` or the entire `root-layout` class

**this is another topic that needs discussing re: css**

2023-06-21 05:38 UTC, bazmurphy commented on client/src/pages/GetInvolvedPage/GetInvolvedPage.css
> +.get-involved-section > h1 {
yes, as alluded to in the pr description and in a comment below, we need to have a big discussion around css, classnames, reusability, globals, etc etc.

so i was doing this without any established patterns

the most obvious one,  as you have noticed is the line dividing the headings from the content below it, and everyone is writing their own version

2023-06-21 05:43 UTC, bazmurphy commented on client/src/pages/GetInvolvedPage/GetInvolvedPage.css
> +}
@ShayanMahnam @VitalinaKuzmenko 
see the comment above about globals
https://github.com/ShayanMahnam/lentegeur-hospital-facility-board/pull/20/files#r1236348059
it also applies to this

2023-06-21 07:52 UTC, ShayanMahnam commented on client/src/pages/GetInvolvedPage/GetInvolvedPage.css
> +}
and no 70% please I mean for now it's ok but remind me to talk about it.
in bigger screens like 30% of my screen is useless 😆

2023-06-21 09:18 UTC, bazmurphy commented on client/src/pages/GetInvolvedPage/GetInvolvedPage.css
> +}
70% here?
In this code comment the 70% relates to the color...
HSL = Hue / Saturation / Lightness
70% Lightness is just a shade of Grey in this case

2023-06-23 13:18 UTC, tiritaki commented
Hi @bazmurphy I think we can add additional box in Volunteer form. What do you think? Should we ask @VitalinaKuzmenko to amend wireframe for this?
![image](https://github.com/ShayanMahnam/lentegeur-hospital-facility-board/assets/12444326/322c3b9e-408d-4119-ace3-0a42740dd2a2)

2023-06-23 20:11 UTC, bazmurphy commented
@tiritaki Added the new requirement (textarea) per the updated Wireframe

2023-06-25 12:16 UTC, VitalinaKuzmenko commented on client/src/pages/GetInvolvedPage/components/DonateSection/DonateSection.css
> +	/* might need a different font-weight? */
Why do you think it might be a different font-weight? 
I think it looks fine for now:)

2023-06-25 12:34 UTC, VitalinaKuzmenko commented on client/src/pages/GetInvolvedPage/components/VolunteerSection/VolunteerForm/VolunteerForm.jsx
> +	// this is deliberately using an "uncontrolled" form
I've never been using uncontrolled form before. 
But as I checked for simple forms it is ok to use uncontrolled form

2023-06-25 12:39 UTC, VitalinaKuzmenko requested changes
Hi @bazmurphy! I reviewed your code. 
1) The thing that you need to change - it's folders. We were talking about that all the components should be inside components folder (not using component inside another component).

2) Another thing that come to my mind:
We can add error input handling which will be displayed for user. 
E.g. If the user provides a name only with 2 character, we can display a message - please provide at least 3 characters.
It is not necessary - let me know what do you think about it.

2023-06-25 14:29 UTC, bazmurphy commented on client/src/pages/GetInvolvedPage/components/VolunteerSection/VolunteerForm/VolunteerForm.jsx
> +		};
this is missing the textarea "message" that was added after a request from the product owner

2023-06-26 09:16 UTC, bazmurphy commented on client/src/pages/GetInvolvedPage/components/DonateSection/DonateSection.css
> +	/* might need a different font-weight? */
I guess I think the "values" are more important than the "labels" because that is what people will focus on if they are trying to enter those details into their banking app when trying to send money

And so they should have more "visual" priority/focus

2023-06-26 09:21 UTC, bazmurphy commented
I have adjusted the PR based on feedback above.

The `loading` class will be in `globals.css` and is added as part of the `Contact Us Page` PR.
So that will not work here because there is no reference to it.

2023-06-26 09:24 UTC, bazmurphy commented
@VitalinaKuzmenko I have adjusted the PR based on the feedback above. And adjusted some other issues I found.

2023-06-26 17:54 UTC, VitalinaKuzmenko commented on client/src/pages/GetInvolvedPage/components/DonateSection/DonateSection.css
> +	/* might need a different font-weight? */
Maybe we can leave it how it is for now. And later to ask a product owner about it.

2023-06-26 17:55 UTC, VitalinaKuzmenko commented on client/src/pages/GetInvolvedPage/components/VolunteerSection/VolunteerForm/VolunteerForm.jsx
> +		};
Yeah...it's true:)

2023-06-27 11:01 UTC, VitalinaKuzmenko approved these changes

2023-06-27 11:04 UTC, merged