1 - About Page - Vitalina
ShayanMahnam/lentegeur-hospital-facility-board pull request #21
Opened 2023-06-20 21:28 UTC by VitalinaKuzmenko

## Description
This PR creates the first iteration of the About Page using the first iteration Wireframes.

## This PR includes:

Adding Components: HistorySection, GovernanceSection, NetworkingSection, Affiliate.
Importing all components into AboutPage
CSS Styling for Mobile First and Desktop

## Related to

Fixes #1

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

2023-06-20 22:09 UTC, ShayanMahnam commented on client/src/pages/AboutPage/components/Affiliate.jsx
> +const Affiliate = ({ image, name }) => {
nice one 👍

2023-06-20 22:10 UTC, ShayanMahnam commented on client/src/pages/AboutPage/components/GovernanceSection.jsx
> +			<div className="title-line"></div>
we need to make this globally we have it everywhere

2023-06-20 22:14 UTC, ShayanMahnam approved these changes
well done everything make sense for me

2023-06-21 05:23 UTC, bazmurphy commented
I will review this (this morning) please hold off on merging until then.

2023-06-21 07:07 UTC, bazmurphy requested changes
Here is My Review 😎 

Please reply to the individual comments/areas if anything needs clarification.

2023-06-21 07:07 UTC, bazmurphy commented on client/src/pages/AboutPage/AboutPage.css
**In terms of file/folder structure:**
We need to discuss if we are having a single css file for a Page
Or having individual css files for each Component
You have taken one approach, and I have taken another approach, so it would be good to decide on one as a team.
I am a fan of having it separated so each Component is "living" alongside its Styles. 
So if i am going to edit a single component I can immediately find its stylesheet with it and can reference it.
But I am happy to hear others opinions


**In terms of images:**
I am interested to know if we will use image containers/wrappers on all of the images - or only some of the images as you have done here.
I have wrapped all of my images, my thinking is it will later help them to behave responsively and scale correctly.
But maybe you have better ideas/opinions on this and I would like to hear them because I am not best practice dynamic image scaling (I should look into this) and I am happy to learn from any of you if you know

**In terms of CSS class naming / specificity:**
We all need to discuss how we want to proceed with class naming conventions and how specific we want to be to set a project standard.

**In terms of margins:**
I think we need to set a standard in terms of element spacing as a team.
My approach was to use either padding internally on the overall parent to push the items away from each other. Or to apply only a bottom margin (no top margin) to the elements that need spacing apart.
Your approach is to apply both top and bottom margins to elements.
I believe that can lead to some issues around consistency of spacing (see attached images).
I hope you can understand the various colours to point of what I mean (if not I can clarify):

So I would like us to agree on how we will do this going forward so I know which one to do in future.

Margins image 1:
![image](https://github.com/ShayanMahnam/lentegeur-hospital-facility-board/assets/61154071/e9f3dac6-d4e7-4af1-8415-cd6152de364c)

Margins image 2:
![image](https://github.com/ShayanMahnam/lentegeur-hospital-facility-board/assets/61154071/2eac41e2-fb70-44c0-85c8-7dc283d1516d)

2023-06-21 07:07 UTC, bazmurphy commented on client/src/pages/AboutPage/AboutPage.css
> +	text-align: justify;
I wanted to ask about this, if we are going to have consistent approaches to centering or justifying etc.

2023-06-21 07:07 UTC, bazmurphy commented on client/src/pages/AboutPage/AboutPage.css
> +}
as we were discussing in the other PR, we need to agree on a set of css globals
this is the most obvious one as we have those grey lines sitting below headings everywhere
and we are all creating them ourselves and slightly differently

2023-06-21 07:07 UTC, bazmurphy commented on client/src/pages/AboutPage/AboutPage.css
> +	width: 50px !important;
we should try to avoid using `!important` unless absolutely neccessary
can we increase the CSS Specificity points another way?
there are a few ways to do that

2023-06-21 07:07 UTC, bazmurphy commented on client/src/pages/AboutPage/AboutPage.css
> +		width: 70px !important;
we should try to avoid using `!important` unless absolutely neccessary
can we increase the CSS Specificity points another way?
there are a few ways to do that

2023-06-21 07:07 UTC, bazmurphy commented on client/src/pages/AboutPage/components/Affiliate.jsx
> +};
The "circle_image" class is not mentioned anywhere in the stylesheets
Also the class naming should make sense in context

Also for accessibility we could pass in the alt text as a prop as well (and store it in the same object we provide thename and image source) see below

```suggestion
const Affiliate = ({ name, image, altText }) => {
	return (
		<div className="affiliate-image-container"> // this classname is adjusted - but its up to you
			<img src={image} alt={altText} className="affiliate-image" /> // this classname is adjusted - but its up to you
			<p>{name}</p>
		</div>
	);
};
```

2023-06-21 07:07 UTC, bazmurphy commented on client/src/pages/AboutPage/components/GovernanceSection.jsx
> +			<div className="title-line"></div>
Yes, we need to discuss this as a team

2023-06-21 07:07 UTC, bazmurphy commented on client/src/pages/AboutPage/components/HistorySection.jsx
> +import image from "../../../assets/grey_image.svg";
```suggestion
import placeHolderImage from "../../../assets/grey_image.svg";
```

2023-06-21 07:07 UTC, bazmurphy commented on client/src/pages/AboutPage/components/HistorySection.jsx
> +				<img src={image} alt="grey square" />
```suggestion
				<img src={placeholderHistoryImage} alt="History alternate text" />
```

2023-06-21 07:07 UTC, bazmurphy commented on client/src/pages/AboutPage/components/NetworkingSection.jsx
> +import image from "../../../assets/grey_image.svg";
```suggestion
import placeholderNetworkingImage from "../../../assets/grey_image.svg";
```

2023-06-21 07:07 UTC, bazmurphy commented on client/src/pages/AboutPage/components/NetworkingSection.jsx
> +import Circle from "../../../assets/grey_circle_image.svg";
if we are importing things like images which are not React Components to keep it clearer could we use Camel case.

```suggestion
import placeholderAffiliateImage from "../../../assets/grey_circle_image.svg";
```

2023-06-21 07:07 UTC, bazmurphy commented on client/src/pages/AboutPage/components/NetworkingSection.jsx
> +	}
Since the above suggestion, here is one to follow from that:
1. if you want to do it dynamically
```suggestion
	const affiliates = Array.from({ length: 6 }, (_, index) => ({
		name: `Affiliate Name ${index + 1}`,
		image: placeholderAffiliateImage,
		altText: `Affiliate alternate text ${index + 1}`,
	}));
```
2. if you want to do it explicitly 
```suggestion
const affiliates = [
		{ name: "Affiliate Name 1", image: placeholderAffiliateImage , altText: "Affiliate alternate text 1" },
		{ name: "Affiliate Name 2", image: placeholderAffiliateImage , altText: "Affiliate alternate text 2" },
		{ name: "Affiliate Name 3", image: placeholderAffiliateImage , altText: "Affiliate alternate text 3" },
		{ name: "Affiliate Name 4", image: placeholderAffiliateImage , altText: "Affiliate alternate text 4" },
		{ name: "Affiliate Name 5", image: placeholderAffiliateImage , altText: "Affiliate alternate text 5" },
		{ name: "Affiliate Name 6", image: placeholderAffiliateImage , altText: "Affiliate alternate text 6" },
	];
```

2023-06-21 07:07 UTC, bazmurphy commented on client/src/pages/AboutPage/components/NetworkingSection.jsx
> +				<img src={image} alt="grey square" />
```suggestion
				<img src={placeholderNetworkingImage} alt="Networking Alternate Text " />
```

2023-06-26 21:10 UTC, ShayanMahnam commented on client/src/pages/AboutPage/components/Affiliate/Affiliate.jsx
> +const Affiliate = ({ image, name }) => {
## suggestion 
Give altText 

```jsx
const Affiliate = ({ image, name, altText })
```

2023-06-26 21:11 UTC, ShayanMahnam commented on client/src/pages/AboutPage/components/Affiliate/Affiliate.jsx
> +				<img src={image} alt="Networking alternate text" />
## suggestion 

```jsx
<img src={image} alt={altText} />
```

2023-06-26 21:15 UTC, ShayanMahnam commented on client/src/pages/AboutPage/components/NetworkingSection/NetworkingSection.jsx
> +						/>
## Suggestion 

```jsx
<Affiliate
	key={affiliate.name}
	image={affiliate.image}
	name={affiliate.name}
        altText={affiliate.altText}
/>
```

2023-06-26 21:19 UTC, ShayanMahnam commented on client/src/pages/AboutPage/components/NetworkingSection/NetworkingSection.css
> +.networking-wrapper {
## suggestion 

```css
.networking-container
```

2023-06-26 21:20 UTC, ShayanMahnam commented on client/src/pages/AboutPage/components/NetworkingSection/NetworkingSection.jsx
> +			<div className="networking-wrapper">
## suggestion 

```css
.networking-container
```

2023-06-26 21:22 UTC, ShayanMahnam commented on client/src/pages/AboutPage/components/HistorySection/HistorySection.jsx
> +			<div className="history-wrapper">
## suggestion

```jsx
<div className="history-container">
```

2023-06-26 21:22 UTC, ShayanMahnam commented on client/src/pages/AboutPage/components/HistorySection/HistorySection.css
> +.history-wrapper {
## suggestion

```css
.history-container
```

2023-06-26 21:22 UTC, ShayanMahnam commented on client/src/pages/AboutPage/components/HistorySection/HistorySection.css
> +	.history-wrapper {
## suggestion

```css
.history-container
```

2023-06-26 21:23 UTC, ShayanMahnam commented on client/src/pages/AboutPage/components/GovernanceSection/GovernanceSection.jsx
> +			<div className="governance-wrapper">
## suggestion

```jsx
<div className="governance-container">
```

2023-06-26 21:24 UTC, ShayanMahnam commented on client/src/pages/AboutPage/components/GovernanceSection/GovernanceSection.css
> +.governance-section {
## suggestion

```css
.governance-container
```

2023-06-26 21:25 UTC, ShayanMahnam commented on client/src/pages/AboutPage/components/GovernanceSection/GovernanceSection.css
> +.governance-wrapper {
## suggestion

```css
.governance-container
```

2023-06-27 08:53 UTC, VitalinaKuzmenko commented on client/src/pages/AboutPage/components/Affiliate/Affiliate.jsx
> +const Affiliate = ({ image, name }) => {
Done :)

2023-06-27 08:53 UTC, VitalinaKuzmenko commented on client/src/pages/AboutPage/components/NetworkingSection/NetworkingSection.jsx
> +						/>
Done :)

2023-06-27 08:55 UTC, VitalinaKuzmenko commented on client/src/pages/AboutPage/components/NetworkingSection/NetworkingSection.css
> +.networking-wrapper {
Done :)

2023-06-27 08:55 UTC, VitalinaKuzmenko commented on client/src/pages/AboutPage/components/NetworkingSection/NetworkingSection.jsx
> +			<div className="networking-wrapper">
Done :)

2023-06-27 09:40 UTC, bazmurphy approved these changes
I have just requested 2 tiny changes 😅 

Then you can merge it 🥳 

( I will approve it now anyway )

2023-06-27 09:41 UTC, bazmurphy commented on client/src/pages/AboutPage/components/NetworkingSection/NetworkingSection.css
> +}
As we discussed/agreed on the Design Philsophy the last section of the page doesn't need a margin-bottom.

```suggestion
.networking-section {
		/* placeholder */
}
```

2023-06-27 09:41 UTC, bazmurphy commented on client/src/pages/AboutPage/AboutPage.jsx
> +			<h1>About LSH</h1>
Let's wait until the Product Owner tells us what they want. LSH has no real meaning here.

```suggestion
			<h1>About</h1>
```

2023-06-27 10:02 UTC, VitalinaKuzmenko commented on client/src/pages/AboutPage/components/NetworkingSection/NetworkingSection.css
> +}
Yes, we need not to forget to add margin to main:)

2023-06-27 10:04 UTC, VitalinaKuzmenko commented on client/src/pages/AboutPage/AboutPage.jsx
> +			<h1>About LSH</h1>
For now I made h1 just "about" (the another one as for me is too long)
Thank you!

2023-06-27 10:24 UTC, merged