6 - Contact Us Page - bazmurphy
ShayanMahnam/lentegeur-hospital-facility-board pull request #23
Opened 2023-06-21 14:47 UTC by bazmurphy

## Description

This PR Creates the first iteration of the **Contact Us Page** using the first iteration Wireframes.

It has the following structure:
- `ContactUsPage` page
  - `ContactUsSection` component
    - `ContactUsForm` subcomponent
  - `VisitUsSection` component
    -  `VisitUsMap` subcomponent

- The ContactUsForm 
  - has required fields
  - is an uncontrolled form by design
  - mocks Form submission handling (check the console) and watch the button

## Issues

- The placeholder text in the textarea is centered, despite me trying various things to align it to the top.
- I am not entirely happy with the way the Map scales, I would like more advanced CSS help on the image scaling and responsiveness and aspect ratio etc. Note it is sitting within a grid cell.
- Eventually this will need to be replaced with an API call to an open source map.
- The CSS is again a problem because we don't have any agreed structure/rules.

## Related to

Issue #6

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have carefully reviewed my own code
- [x] I have commented my code
- [x] ~I have updated any documentation~ Not currently neccessary

2023-06-25 19:52 UTC, VitalinaKuzmenko commented on client/src/pages/ContactUsPage/components/ContactUsForm/ContactUsForm.jsx
> +						First Name *
Instead of First Name it should be Phone Number

2023-06-25 19:52 UTC, VitalinaKuzmenko commented on client/src/pages/ContactUsPage/components/ContactUsForm/ContactUsForm.jsx
> +						required
phone number is not required

2023-06-25 19:59 UTC, VitalinaKuzmenko commented on client/src/pages/ContactUsPage/components/ContactUsForm/ContactUsForm.jsx
> +						pattern="^\+?[0-9]+$"
The HTML validation pattern you have provided, pattern="^\+?[0-9]+$", expects the input to only contain digits after an optional "+" symbol at the beginning. However,  if the user provides the value like "+27 77 555 5555", which includes spaces and hyphens, which already do not match the pattern.

pattern="^\+?[0-9\s-]+$"
This pattern allows for digits, spaces, and hyphens in the input, in addition to the optional "+" symbol at the beginning.

2023-06-25 20:06 UTC, VitalinaKuzmenko commented on client/src/pages/ContactUsPage/components/ContactUsForm/ContactUsForm.jsx
> +						defaultValue={""} // i don't think this is the best practice...
I checked this defaultValue in Internet - it seems to be ok ;)

2023-06-25 20:12 UTC, VitalinaKuzmenko commented on client/src/pages/ContactUsPage/components/ContactUsForm/ContactUsForm.jsx
> +									key={index}
I know it's a bad practise to use index as a unique key. Because someone can delete, update any of the elements of the array.

So maybe it would be better to write like this:
key={reason + index}
In this way, we make sure that the key is always unique

2023-06-25 20:38 UTC, VitalinaKuzmenko commented on client/src/pages/ContactUsPage/components/ContactUsForm/ContactUsForm.jsx
> +	const reasons = ["Reason option 1", "Reason option 2", "Reason option 3"];
I thinkg we can already put 3 options which we have at the moment:

const reasons = ["Compliments", "Complains", "Suggestions"];

2023-06-25 20:40 UTC, VitalinaKuzmenko commented on client/src/pages/ContactUsPage/components/ContactUsForm/ContactUsForm.jsx
> +		// formRef.current.reset();
Why did you comment this line? formRef.current.reset();

I think we need to uncomment it:)

2023-06-25 20:57 UTC, VitalinaKuzmenko commented on client/src/pages/ContactUsPage/components/ContactUsForm/ContactUsForm.css
> +/* this loading animation needs to be global */
I think you can transfer this class with loading animation to globals.css now

2023-06-25 21:01 UTC, VitalinaKuzmenko commented on client/src/pages/ContactUsPage/components/VisitUsSection/VisitUsSection.css
> +	/* may want a gap here */
yes,
we can put 
gap: 5px;

2023-06-25 21:02 UTC, VitalinaKuzmenko commented on client/src/pages/ContactUsPage/components/VisitUsSection/VisitUsSection.css
> +	/* for custom Address and Contacts styling */
We can put
font-weight: 600;

What do you think about it?

2023-06-25 21:07 UTC, VitalinaKuzmenko commented on client/src/pages/ContactUsPage/ContactUsPage.css
> +@media screen and (min-width: 768px) {
We don't need this media query. We don't change anything

2023-06-25 21:30 UTC, VitalinaKuzmenko commented on client/src/pages/ContactUsPage/components/VisitUsSection/VisitUsSection.css
> +}
We can add here:
margin-botton: 30px;

To make some space between section and a footer:)

2023-06-25 21:39 UTC, VitalinaKuzmenko requested changes
Hi, @bazmurphy ! Please enjoy my code review:)
I spend more than one hour reviewing your code:)

You can find some comments to your code.

1. I think the same as with volunteer form - we can add some error handling for input in the form. E.g. for the textarea maxlength=300 characters. If it will be more: we need to display message: Maximum length of the message is 300 characters.
But I thinkg it's better to leave this functionality for another ticket.

2. The mobile design of VisitUs Section is wrong. Check with wireframes.
We need to have first - address, then - map, and then - contacts.


Below you will find my implemanation for this.
1. First you need to delete div:
<div className="visit-us-details-container">
Because we need to have addres and contacts and map at the same level in one div.

2. We need to add extra class for address and contacts div:
<div className="address visit-us-details-subcontainer">
<div className="contacts visit-us-details-subcontainer">

3. Then you need to change css inside VisitUsSection.css.

- create a template for mobile version using grid-template-areas. I added also a margin-top to seperate this container from the line. (or should we add margin-bottom to the line???)
.visit-us-container {
	display: grid;
	margin-top: 30px;
	row-gap: 30px;
	grid-template-areas:
		"address"
		"map"
		"contacts";
}

- adding grid-area to address, contacts and map. (I also added margin-left to address and contacts for mobile version)
.address {
	grid-area: address;
	margin-left: 30px;
}

.contacts {
	grid-area: contacts;
	margin-left: 30px;
}
.visit-us-map-container {
	grid-area: map;
	width: 100%;
	height: 400px;
	border: 1px solid var(--black);
}

- to modify desktop version:
@media screen and (min-width: 768px) {
	.visit-us-container {
		grid-template-columns: 0.3fr 0.7fr;
		grid-template-areas:
			"address map"
			"contacts map";
	}

.address, .contacts {
		margin-left: 0;
	}
}

And now you don't have a problem with map flushing from the right.

Let me know If you have any questions. I will be happy to help you:)

2023-06-26 09:00 UTC, bazmurphy commented on client/src/pages/ContactUsPage/components/ContactUsForm/ContactUsForm.jsx
> +						First Name *
Yes 👍

2023-06-26 09:00 UTC, bazmurphy commented on client/src/pages/ContactUsPage/components/ContactUsForm/ContactUsForm.jsx
> +						required
Yes 👍

2023-06-26 09:00 UTC, bazmurphy commented on client/src/pages/ContactUsPage/components/ContactUsForm/ContactUsForm.jsx
> +						pattern="^\+?[0-9]+$"
I was wondering about this, it is my instinct to type a phone number in as all one long set of numbers, (but that doesn't mean all users will do this), so you are right it should allow spaces also.

However... see the big review comment below about why I will remove the pattern because of an upcoming ticket around Live Form Input Validation / Error Handling etc.

As a note to the team and myself we should lookup decent validator libraries.

2023-06-26 09:00 UTC, bazmurphy commented on client/src/pages/ContactUsPage/components/ContactUsForm/ContactUsForm.jsx
> +						defaultValue={""} // i don't think this is the best practice...
Yea i looked it up a bit more, the defaultValue={} sets the inital option but after that React doesn't track it anymore. 
And this is useful on uncontrolled forms like the one I made (where there is no use of value={}. 
I just don't like the initial Value being an empty string `""` because it's not explicit enough. 
And making the first hardcoded default option that is unselectable a value of empty string `""` I also do not like.
Feels hacky.

Hmmm....

2023-06-26 09:00 UTC, bazmurphy commented on client/src/pages/ContactUsPage/components/ContactUsForm/ContactUsForm.jsx
> +									key={index}
About the index, yes and no.
Because in this case who would be editing those select options (to add/delete/update) they will be hardcoded right?
Maybe this becomes an issue if we are populating these select options with backend code, in which case yes I agree but I would then give them ids.
So I will construct the array that it gets the options from with ids instead. And use those as the keys. So that its futureproof.
Although I guess most people would argue the "reason" string on it's own can be a unique key as its a specific set of string characters that will not be repeated because it doesn't make sense if there are two options that are the exact same on a form select option list.

2023-06-26 09:00 UTC, bazmurphy commented on client/src/pages/ContactUsPage/components/ContactUsForm/ContactUsForm.jsx
> +	const reasons = ["Reason option 1", "Reason option 2", "Reason option 3"];
Yes, I wasn't sure what exact values they wanted. 
I will adjust them to these for now and include id's as commented above.
But we need to check with the Product Owner for what options they really want.

2023-06-26 09:00 UTC, bazmurphy commented on client/src/pages/ContactUsPage/components/ContactUsForm/ContactUsForm.jsx
> +		// formRef.current.reset();
Yes, I was playing around with it when making fake submissions and forgot to uncomment it 😵

2023-06-26 09:00 UTC, bazmurphy commented on client/src/pages/ContactUsPage/components/ContactUsForm/ContactUsForm.css
> +/* this loading animation needs to be global */
I just threw this class together very quickly, it's not perfect.
And it only applies to this specific button and its hardcoded in height/width which is not good.
I would really like to come up with some sort of "scalable" loading animation that we can use in multiple places and that "just fits" into whatever button or element you put it inside.
I think that is a better solution.
This was kind of a "proof of concept"
But I will move it and someone can adjust it later.

2023-06-26 09:00 UTC, bazmurphy commented on client/src/pages/ContactUsPage/components/VisitUsSection/VisitUsSection.css
> +	/* may want a gap here */
Ok 👍

2023-06-26 09:00 UTC, bazmurphy commented on client/src/pages/ContactUsPage/components/VisitUsSection/VisitUsSection.css
> +	/* for custom Address and Contacts styling */
Yes, Good👍

2023-06-26 09:01 UTC, bazmurphy commented on client/src/pages/ContactUsPage/ContactUsPage.css
> +@media screen and (min-width: 768px) {
This was a deliberate placeholder so that when people go back and want to adjust the difference between the Mobile and Desktop Page left/right margins they can. (Because I don't think Mobile/Desktop left/right margins should be the same - usually Desktop has more "space"(?)).

Are we planning on having them the same?

2023-06-26 09:01 UTC, bazmurphy commented on client/src/pages/ContactUsPage/components/VisitUsSection/VisitUsSection.css
> +}
See big comment after about Design Philosophy.

2023-06-26 09:01 UTC, bazmurphy commented
Thank you very much for a thorough review! 😎 👏👏 
This is how we work together to make a great product 😄

**0. Form Validation:** 
Live Form Input Validation and Error Handling adds a lot more to these tickets (which I already think have gone above their scope). Also there was no specific design or agreement on how that will work or for me to follow about where we want the errors to show and how etc, so I would be guessing and I would rather do that when I know what we want. 
We can do it sure, but maybe we merge the tickets first like you said, and then create new tickets for that. And if you want the Input Validation done live with live feedback the Forms will have to be converted from Uncontrolled to Controlled. (I have actually already started work on that locally because I saw it was heading in this direction.)
(So it is better i remove all `pattern`s as that would be handled in the Live Input Validation tickets)

**1. About textarea max length:**
We don't know how long of a message a person will want to write to them. Maybe they have a lot to say about a specific situation if it is a complaint for example. So until we find out from the Product Owner we shouldn't enforce a limit we just come up with. But yes I agree a limit as an idea is good 👍

**2. About map layout:** 
Yes I did make it like that first, and then I thought the "visual flow" (and look) is much worse, which is why i did it like this. 
I also didn't like the map fully aligned to the right again because of the "visual flow" (and look) (because the address was indented left. But yes I should not do this without asking with the team first that is true. So I will make a post on Slack showing the differences between two and ask for opinion.  And you have given me the css to do that quickly so thats great 👍 Thanks

**3. About margin-bottom & Design Philosophy:**
The general design philosophy in terms of the box model I am trying to use is (see image I made) 
![image](https://github.com/ShayanMahnam/lentegeur-hospital-facility-board/assets/61154071/8e9a40c0-d1ae-4e47-a04b-13a381d666b0)

![Screenshot 2023-06-26 at 09-11-22 Lentegeur Hospital Facility Board](https://github.com/ShayanMahnam/lentegeur-hospital-facility-board/assets/61154071/13fe111d-de10-4997-8af0-6681d9e435cb)

Because it makes **the most sense to me** that we move the overall control to the highest element of the hierarchy(tree). So that we do not have to repeat things further down.

In a perfect world `<main>` should be controlling both top/bottom margins (from the header and footer) and left/right margins (from the edge of the browser)... and the Page itself would not need to include that information. 
But because of Home Hero like we discussed it can't work exactly like that.

So instead `<main>` should keep control of the top/bottom margin (from the header and footer) and we should then give the "next child down" the control of margin left/right which in this case is the `Page` `<div>`

![image](https://github.com/ShayanMahnam/lentegeur-hospital-facility-board/assets/61154071/b8aba846-86ba-4b5a-9e3e-864badd3cf29)

Does this make sense to you?

And so in this way the final `<section>` on any page **should not have** any `margin-bottom` because `<main>` margin-bottom is already achieving this.

2023-06-26 18:03 UTC, VitalinaKuzmenko commented on client/src/pages/ContactUsPage/components/ContactUsForm/ContactUsForm.jsx
> +						defaultValue={""} // i don't think this is the best practice...
When we will change form into controlled we can change it into:

const [selectedReason, setSelectedReason] = useState("");

const handleReasonChange = (event) => {
  setSelectedReason(event.target.value);
};

// ...

<select
  id="contact-us-form-reason"
  name="reason"
  value={selectedReason}
  className="contact-us-form-select"
  onChange={handleReasonChange}
  required
>
  <option disabled value="" className="contact-us-form-option">
    Please select a reason...
  </option>
  {reasons.map((reason, index) => (
    <option
      key={index}
      className="contact-us-form-option"
      value={reason}
    >
      {reason}
    </option>
  ))}
</select>

2023-06-26 18:05 UTC, VitalinaKuzmenko commented on client/src/pages/ContactUsPage/components/ContactUsForm/ContactUsForm.jsx
> +									key={index}
Ok :)

2023-06-26 18:06 UTC, VitalinaKuzmenko commented on client/src/pages/ContactUsPage/components/ContactUsForm/ContactUsForm.css
> +/* this loading animation needs to be global */
Or we will create a Button component and then we can put this animation class to there Button.css
Ok:)

2023-06-26 18:08 UTC, VitalinaKuzmenko commented on client/src/pages/ContactUsPage/ContactUsPage.css
> +@media screen and (min-width: 768px) {
I was thinking to have them the same. Because for desktop version I think we don't need bigger margin - because we have max-width: 1200px and then we have space from the left and right....

2023-06-26 18:09 UTC, VitalinaKuzmenko commented on client/src/pages/ContactUsPage/components/VisitUsSection/VisitUsSection.css
> +}
ok:)

2023-06-26 18:14 UTC, VitalinaKuzmenko commented
Yes, I agree with Design Philosophy:) And we can discuss this mobile view for VisitUs page on today's Stand Up.

You can read some of my answers above and merge this branch to development branch:) Good job:)

2023-06-27 10:59 UTC, bazmurphy commented
@VitalinaKuzmenko if there are no more issues, can you change this to Approved

2023-06-27 11:02 UTC, bazmurphy commented on client/src/pages/ContactUsPage/ContactUsPage.css
> +@media screen and (min-width: 768px) {
are you sure 20px margin on desktop (before 1200px) is going to look ok? Usually Desktop designs have more "white space" than mobile designs.

We need to set a standard for this across all "Pages"

2023-06-27 11:02 UTC, VitalinaKuzmenko approved these changes

2023-06-27 11:03 UTC, merged